### ISSUE TITLE
Send checkbox information to backend

### ISSUE THREAD

**Issue by raechiang** [Optimize-Prime-CS480-Cal-Poly-Fall17/demo-web-project#10]

**Comment by toddnguyen47** [comment]
@raechiang Basic template for our homepage done! We now need to figure out how to send the checkboxes information to the backend.

**Comment by raechiang** [comment]
**Category Considerations**: American (Traditional), Asian Fusion, Korean, Lebanese, British, Mexican, American (New), Vietnamese, Japanese, Korean, Hawaiian, Mediterranean, Middle Eastern, Halal, Argentine, Chinese, Filipino, Italian, Latin American, Lebanese, Thai, Indian, Tex-Mex

**Also**: Vegan, Soup, Tapas/Small Plates, Poutineries, Fruits & Veggies, Cheesesteaks, Falafel, Poke, Fish & Chips, Comfort Food, Waffles, Pizza, Juice Bars & Smoothies, Empanadas, Salad, Barbeque, Chicken Wings, Coffee & Tea, Hot Dogs, Burgers, Sandwiches, Seafood, Tacos, Ice Cream & Frozen Yogurt, Shaved Ice

I grabbed these from Yelp, but I may have missed some. I know I missed some for the lower list because I didn't originally plan to grab those types of categories.
