### ISSUE TITLE
Information require/need to include for foodtruck (TruckInfo) object; Please list in comment.

### ISSUE THREAD

**Issue by johnHaloWang** [Optimize-Prime-CS480-Cal-Poly-Fall17/demo-web-project#13]

**Comment by raechiang** [comment]
I think that we need at least the following: **name**, **type**, **lat**, **lon**, **address** (with zip_code?), **phone_number**.
Then maybe also an image and schedule/hours if possible.
Feel free to reject or support any of the items in the list(s) above.
