### ISSUE TITLE
Front End - HTML Table & Button

### ISSUE THREAD

**Issue by toddnguyen47** [Optimize-Prime-CS480-Cal-Poly-Fall17/demo-web-project#2]
Learn how HTML works, and see if you can create a nice table and a "Search" button.

**Comment by raechiang** [comment]
Hi, I added something [here](https://github.com/Optimize-Prime-CS480-Cal-Poly-Fall17/demo-web-project/tree/master/src/main/resources/static/practice). I'm not sure if it's sufficient or entirely proper, but the instructions seemed pretty lenient. I skipped the search button, but I'll definitely look into implementing a real search button.

**Comment by toddnguyen47** [comment]
Perfect, thank you @raechiang !
