### ISSUE TITLE
Extract table data from Javascript & place it in HTML table

### ISSUE THREAD

**Issue by toddnguyen47** [Optimize-Prime-CS480-Cal-Poly-Fall17/demo-web-project#8]
Use AngularJS if possible.

**Comment by raechiang** [comment]
@toddnguyen47 I used AngularJS to attempt this issue. I pulled directly from the json file, but I hope that's okay ([view](https://github.com/Optimize-Prime-CS480-Cal-Poly-Fall17/demo-web-project/tree/master/src/main/resources/static)). The HTML page is "foodTruckTest.html".

**Comment by johnHaloWang** [comment]
@raechiang plz check out the demo for front end; I believe we can get away from using json
